spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: liugogal
    password: gogalggoo
    url: jdbc:mysql://47.91.165.146:3306/cloud?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
  cloud:
    stream:
      bindings:
        input:
          destination: mqTestDefault
        output:
          destination: mqTestDefault
          #contentType: text/plain
env:
  test1984133
