spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: liugogal
    password: gogalggoo
    url: jdbc:mysql://47.91.165.146:3306/cloud?characterEncoding=utf-8&useSSL=fals  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
